### ISSUE TITLE
Alexa does not set temperature 

### ISSUE THREAD

**Issue by JulianGold** [sinricpro/esp8266-esp32-sdk#161]
Setting temperature from Alexa results in “sorry, device is not responding”. Setting a temperature increment or turning thermostat on or off works. Temperature setting in Alexa is in Fahrenheit.

**Comment by kakopappa** [comment]
1. Do you see any errors in the activity log?
2. are you returning true after handling the set onTargetTemperature?
https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Thermostat/Thermostat.ino#L53

**Comment by sivar2311** [comment]
Did you implement an onAdjustCallback and attached this to your device?

**Comment by JulianGold** [comment]
1. There are no errors in the log. The onTargetTemperature  function is not called
2. Yes, I am returning true in the onTargetTemperature function. However, the function is not triggered. 

The other "events" such as increasing or decreasing the temperature work well. Setting the temperature to a specified level however does not work from Alexa. It does work from the SinricPro mobile app but it does not work from Alexa.

**Comment by sivar2311** [comment]
Does this happen with unmodified [example sketch](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/examples/Thermostat/Thermostat.ino)?
Which SDK Version do you use?
Do you see incoming requests when debugging is enabled?

**Comment by JulianGold** [comment]
The issue occurs with the example sketch. 
I am using SDK 2.9.1. The issue occurred in the past, at least since 2.8.1.
I did not test with debug enabled yet.
The callback is attached.

The issue might be due to Alexa working with Fahrenheit vs Celsius but I'm not sure.

**Comment by sivar2311** [comment]
Does it get triggered when using portal.sinric.pro ?
Which scale did you set in your SinricPro account?

**Comment by sivar2311** [comment]
Ok, i could reproduce it - we will check this.

**Comment by sivar2311** [comment]
Can you tell me where exactly the error occurs?
- SinricPro Portal
- Alexa voice input
- Alexa App

**Comment by JulianGold** [comment]
Alexa app as well as Alexa voice input. 
SinricPro portal works well.

**Comment by sivar2311** [comment]
Fixed in 2.9.2 ✔️ 
Please update and check again.

**Comment by JulianGold** [comment]
Retested and it's a bit better. The message is received and callback triggered. 
The temperature received in the message however is always 17.8888 degrees lower than it should be.
For example if I ask Alexa to set the temperature to 70, the message received at micro-controller device says "52.22222"

**Comment by sivar2311** [comment]
Yeah, i had the same issue and thought it is related to my DE settings.
Issue in sdk is fixed.
@kakopappa can you check whats going on ?

**Comment by kakopappa** [comment]
Hi @JulianGold  

There was an issue on the server-side and I have fixed it. Please give it a go when you get a chance

**Comment by JulianGold** [comment]
👍  Works great now. Thank you!

**Comment by JulianGold** [comment]
Perhaps less important (for me) but the SinricPro iOS App is still showing the target temperature off by 8 degrees.

**Comment by kakopappa** [comment]
Is the portal showing the correct value?

**Comment by JulianGold** [comment]
Yes, the portal shows the right temperature now. The iOS app is the one that is not showing the right target temperature.

**Comment by kakopappa** [comment]
Hello @JulianGold 

Thank you for letting us know. I will look into this and update this issue again when it's fixed.

I going to move this issue out of the sdk repo to non-sdk repo since it's no longer an SDK issue.
