### ISSUE TITLE
Device did not handle set power state.

### ISSUE THREAD

**Issue by Trinnss** [sinricpro/esp8266-esp32-sdk#361]
I am using a dht20 sensor and esp01s for temperature which uses i2c communication check this code and inform me about the fault.
the device is connected to the Sinricpro dashboard but when clicking turn on or off it shows an error that the "device did not handle "set power state"". I have removed the credentials.
[DHT20_sinric.zip](https://github.com/sinricpro/esp8266-esp32-sdk/files/13818526/DHT20_sinric.zip)
Please solve it as soon as possible.

**Comment by sivar2311** [comment]
Hello @Trinnss!

Since version 3.x, the sensors no longer supports switching on and off - see [changelog](https://github.com/sinricpro/esp8266-esp32-sdk/blob/master/changelog.md#version-300)
However, it seems that the GUI still shows the buttons for switching on and off.

@kakopappa Can you remove the buttons from the GUI, please?

> Please solve it as soon as possible.

I wish you a happy new year too!

**Comment by kakopappa** [comment]
fixed. released a new version of portal v2.40.4

**Comment by Trinnss** [comment]
I have seen some bugs.
temperature block in the GUI of the website does not show temperature but shows humidity and Amazon Alexa and Sinric Pro app still show power button.

**Comment by sivar2311** [comment]
> temperature block in the dashboard GUI of the website does not show temperature

Do you see the temperature in serial monitor when the sketch is running?
Please post the content of your serial monitor.

**Comment by kakopappa** [comment]
Thanks for reporting. Issue has been fixed v2.40.5

![image](https://github.com/sinricpro/esp8266-esp32-sdk/assets/7474406/bd031c5e-1e89-403d-816d-2ddca868faec)

**Comment by Trinnss** [comment]
please check about the alexa and google skills .
Where switch is still present

**Comment by kakopappa** [comment]
Google Home shows as a thermostat due to limitations in Google Home

what’s wrong with Alexa?

**Comment by Trinnss** [comment]
both shows switch to turn on or off the device.

**Comment by kakopappa** [comment]
Hi @Trinnss 

Alexa app is out of our control
